version: "3.9"

services:

  app:
    build: .
    container_name: livroapi_app
    environment:
      - HOST=postgres
      - USER=candidato
      - PASSWORD=123456
      - DBNAME=livroapidb
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - livroapi_network

  postgres:
    image: postgres:13-alpine
    container_name: livroapi_postgres
    environment:
      - POSTGRES_USER=candidato
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=livroapidb
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U candidato -d livroapidb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - livroapi_network

networks:
  livroapi_network:
    driver: bridge
